ansible-navigator:
  execution-environment:
    container-engine: docker
    image: harbor.blockgateway.net:8081/library/mainnet_ansible:v1
    pull:
      policy: missing
    volume-mounts:
      - src: "."
        dest: "/ansible"
      - src: "."
        dest: "/runner/project"
    environment-variables:
      pass:
        - VAULT_ADDR
        - VAULT_TOKEN
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY

