ansible-navigator:
  execution-environment:
    container-engine: docker
    image: harbor.blockgateway.net/library/ee:v1
    pull:
      policy: missing
    volume-mounts:
      - src: "."
        dest: "/ansible"

    environment-variables:
      pass:
    #     - VAULT_ADDR
    #     - VAULT_TOKEN
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY

