name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # 1. Harbor 레지스트리에 로그인하는 단계 추가
    - name: Login to Harbor
      uses: docker/login-action@v3
      with:
        registry: harbor.blockgateway.net
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - name: Build and push the Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true 
        tags: harbor.blockgateway.net/library/test:$(date +%s)
