name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # 1. Harbor 레지스트리에 로그인하는 단계 추가
    - name: Login to Harbor
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.HARBOR_URL }}
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - name: Build and push the Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true 
        tags: ${{ secrets.HARBOR_URL }}/library/test:v1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_URL }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Install Ansible Navigator
        run: pip install ansible-navigator

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: arn:aws:iam::868422696150:role/InfraServer
      #     aws-region: ap-northeast-1
      - name: Install docker collection
        run: |
          pip install docker
          pip install ansible
          ansible-galaxy collection install community.docker
          ansible-galaxy collection install -r ansible/execution-environment/requirements.yml --force

      - name: Run Ansible Navigator
        run: |
          ansible-navigator run ansible/playbook.yml \
            -i ansible/inventory.yml \
            --mode stdout
 


